
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NAAuthProvider } from '@/providers/NAAuthProvider';
import AppBar from '@/components/AppBar';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>This is root Layout</div>
        <NAAuthProvider>
        <AppBar />
          {children}
          </NAAuthProvider>
        <div> This is Layout Bottom</div>
      </body>
    </html>
  )
}
