
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthContexProvider } from '@/providers/AuthContexProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>This is root Layout</div>
        <AuthContexProvider>
          {children}
          </AuthContexProvider>
        <div> This is Layout Bottom</div>
      </body>
    </html>
  )
}
